server:
  port: 9002
idiomui:
  prefix: "传统文化: "
hystrix:
  metrics:
    enabled: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 12000  